before_script:
- cp .sample.env .env
- bin/rake db:setup --trace
bundler_args: "--deployment --jobs=3 --retry=3 --without development"
cache: bundler
env:
- DB=postgresql
language: ruby
rvm:
- ruby-2.2.3
sudo: false
script:
- bundle exec rake
